language: c
sudo: false

addons:
  apt:
    packages:
    - cpanminus
    - perl

install:
  - cpanm --quiet --notest --skip-satisfied Test::Nginx
  - cpanm --quiet --notest --skip-satisfied Test::Nginx::Socket
  - git clone https://github.com/yaoweibin/ngx_http_substitutions_filter_module
  - curl http://nginx.org/download/nginx-1.6.0.tar.gz > nginx-1.6.0.tar.gz
  - tar xzf nginx-1.6.0.tar.gz
  - cd nginx-1.6.0
  - find /home/travis -name Socket.pm
  - ls -lR /home/travis/perl5

script: 
  - ./configure --add-module=../ngx_http_substitutions_filter_module --add-module=.. && make
  - PATH=objs:$PATH prove -r ../t -I ~/perl5
  